# Generated by Django 3.2.10 on 2021-12-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_productmodel_ctg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karzinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_k', models.CharField(max_length=250)),
                ('image_k', models.IntegerField()),
                ('price_k', models.IntegerField()),
                ('username', models.CharField(max_length=250)),
                ('catrgory_k', models.CharField(max_length=250)),
                ('soni', models.IntegerField(default=1)),
                ('total_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
