# Generated by Django 3.2.10 on 2021-12-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_karzinka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karzinka',
            name='image_k',
            field=models.ImageField(upload_to=''),
        ),
    ]
