# Generated by Django 3.2.10 on 2021-12-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_karzinka_image_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='karzinka',
            name='date_k',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='karzinka',
            name='is_delier',
            field=models.BooleanField(default=False),
        ),
    ]
